#!/bin/sh
# chkconfig: 45 99 99
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/python
NAME=CheckIn
DESC="CheckIn Daemon"
OPTS="/usr/local/CheckIn/checkin.py"
PIDFILE=/var/run/$NAME.pid
. /lib/lsb/init-functions


case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --background -x "$DAEMON" -- $OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	sleep 1
	start-stop-daemon --start --background -x "$DAEMON" -- $OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/checkin
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
