#!/bin/sh
# chkconfig: 45 99 99
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/CheckIn/web/http.py
NAME=CheckIn-Web
DESC="CheckIn Web Service"
PIDFILE=/var/run/$NAME.pid
. /lib/lsb/init-functions


case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --background -x "$DAEMON"
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	sleep 1
	start-stop-daemon --start --background -x "$DAEMON"
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/checkin-web
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
