#!/bin/sh
# chkconfig: 45 99 99
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/CheckIn/checkin.py
NAME=CheckIn
DESC="CheckIn Daemon"
PIDFILE=/var/run/$NAME.pid
. /lib/lsb/init-functions


case "$1" in
  start)
	echo -n "Starting $DESC: "
	echo -n 4 > /sys/class/gpio/export
	echo -n 40 > /sys/class/gpio/export
	echo -n 41 > /sys/class/gpio/export
	echo -n "out" > /sys/class/gpio/gpio4/direction
	echo -n "out" > /sys/class/gpio/gpio40/direction
	echo -n "out" > /sys/class/gpio/gpio41/direction
    echo -n "1" > /sys/class/gpio/gpio4/value
	echo -n "0" > /sys/class/gpio/gpio40/value
	echo -n "0" > /sys/class/gpio/gpio41/value
	start-stop-daemon --start --background -x "$DAEMON"
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	echo CLEAR > /dev/ttyS0
	echo BEEP > /dev/ttyS0
	echo BEEP > /dev/ttyS0
	echo WShutting down... > /dev/ttyS0
	sleep 2 
	echo CLEAR > /dev/ttyS0
	echo -n 4 > /sys/class/gpio/unexport
	echo -n 40 > /sys/class/gpio/unexport
	echo -n 41 > /sys/class/gpio/unexport
	start-stop-daemon --stop -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	sleep 1
	start-stop-daemon --start --background -x "$DAEMON"
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/checkin
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
