#!/bin/bash
echo CLEAR > /dev/ttyS0
echo BEEP > /dev/ttyS0  
echo BEEP > /dev/ttyS0
echo BEEP > /dev/ttyS0
echo WShutting down... > /dev/ttyS0
sleep 3
echo CLEAR > /dev/ttyS0
echo -n 40 > /sys/class/gpio/unexport
echo -n 41 > /sys/class/gpio/unexport
echo -n 4 > /sys/class/gpio/unexport
killall python
