#!/bin/bash

#JTAGICE3 pins	Target		Squid	ISP pinout	Arduino Pin
#Pin 1 (TCK)	SCK			1				3	13
#Pin 2 (GND)	GND			2				6	GND
#Pin 3 (TDO)	MISO		3				1	12
#Pin 4 (VTG)	VTG			4				2	VCC
#Pin 5 (TMS)	 			5	 
#Pin 6 (nSRST)	/RESET		6				5	RESET
#Pin 7 (NC)	 				7	 
#Pin 8 (nTRST)	 			8	 
#Pin 9 (TDI)	MOSI		9				4	11
#Pin 10 (GND)	 			0	 

avrdude -p m328p -c jtag3isp -B 0.5 -U flash:w:./.build/uno/firmware.elf
